name: NPM Publish
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: wasm-pack build --target web
      - run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: npm publish ./pkg
