name: PyPI Publish
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist
      - name: Publish to PyPI
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: maturin upload dist/*
